config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :articles do
   resources :comments
  end
  resources :contacts
  root to: 'pages#index'
  get 'pages/contact'
  get 'pages/about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
 belongs_to :user
 has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :message

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(params[:comment].permit(:body))
    @comment.user_id = current_user.id if current_user

    if @comment.save
       redirect_to article_path(@article), notice: "Your comment has been saved."
    else
       redirect_to 'new'
   end

 end

  def update
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])

    if @comment.update(params[:comment].permit(:body))
       redirect_to article_path(@article), notice: "Your comment has been updated."
    else
       render 'edit'
    end
  end

  def edit
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), notice: "Your comment has been deleted."
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
   @contact = Contact.new
  end

  def create
   @contact = Contact.new(contact_params)
   if @contact.save
    redirect_to root_path
    name = params[:contact][:name]
    email = params[:contact][:email]
    message = params[:contact][:message]
    ContactMailer.contact_email(name, email, message).deliver
    flash[:success] = "Thanks for the message, we will be in touch soon."
   else
    redirect_to pages_contact_path
    flash[:danger] = "Opps, there was a problem! Please fill out all the fields."
  end
 end

 private

 def contact_params
  params.require(:contact).permit(:name, :email, :message)
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
   @article = Article.last(5)
  end

  def contact
   @contact = Contact.new
  end

  def about
  end
end

app/controllers/registrations_controller.rb
    class RegistrationsController < Devise::RegistrationsController

        private

        def sign_up_params
          params.require(:user).permit(
            :email,
            :password,
            :password_confirmation,
            :username,
            :firstname,
            :lastname
            )
        end

        def account_update_params
          params.require(:user).permit(
            :email,
            :password,
            :password_confirmation,
            :current_password,
            :username,
            :firstname,
            :lastname
            )
        end
      end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render 'comments/comments' %>


<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="row">

   <!-- Blog Post Content Column -->
   <div class="col-lg-8">

    <!-- Blog Post -->

    <!-- Title -->
    <h1 style="font-size: 62.5px;">
     <%= @article.title %>
    </h1>

    <!-- Author -->
    <p class="lead">
     <%= @article.user.username %>
    </p>

    <hr>

    <!-- Date/Time -->
    <p><span class="glyphicon glyphicon-time"></span> Was Posted:

    <hr>

    <!-- Preview Image -->

    <hr>

    <!-- Post Content -->
    <%= @article.body %>
    <hr>

    <!-- Blog Comments -->

    <%= render @article.comments %>

    <!-- Comments Form -->
    <%= render 'comments/form' %>
    <div class="card my-4">
          <h5 class="card-header">posted comments:</h5>
          <div class="card-body">
            <form>
              <div class="form-group">
                blablabla
              </div>

            </form>
          </div>
        </div>

    <hr>

    <!-- Posted Comments -->

    <!-- Comment -->

   </div>

   <!-- Blog Sidebar Widgets Column -->
   <div class="col-md-4">

    <!-- Blog Search Well -->

    <!-- Blog Categories Well -->

    <!-- Side Widget Well -->
    <div class="well">
     <h4></h4>

    </div>

  </div>

</div>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<div class="media">
  <div class="pull-left">

       <%= comment.user.username %>

  </div>
  <div class="media-body">
      <p class="media-heading pull-right">
        <%= time_ago_in_words(comment.created_at) %>
      </p> <br />

       <%= comment.body %>

  </div>
</div>



      <%= link_to "Edit", edit_article_comment_path(comment.article, comment) %>

<%= link_to "Delete", [comment.article, comment], method: :delete, data: { confirm: "Are you sure?" } %>

app/views/comments/_form.html.erb
<%= simple_form_for ([@article, @article.comments.build]) do |f| %>

<%= f.input :body %>
<%= f.submit "post your commit" %>

<% end %>

app/views/comments/edit.html.erb
<h1> Edit Comment</h1>

<%= simple_form_for([@article, @comment]) do |f| %>
	<%= f.input :body %>
	<%= f.submit %>

	<% end %>

app/views/layouts/_foot.html.erb
<footer class="footer-distributed navbar fixed-bottom">

    <div class="footer-right">

	<a href="#"><i class="fa fa-facebook"></i></a>
	<a href="#"><i class="fa fa-twitter"></i></a>
	<a href="#"><i class="fa fa-linkedin"></i></a>
	<a href="#"><i class="fa fa-github"></i></a>

    </div>

    <div class="footer-left">

	<p class="footer-links">
	·
	<%= link_to "Contact Us", pages_contact_path, class: "page-scroll" %>
	·
	<%= link_to "About Us", pages_about_path, class: "page-scroll" %>
	·
	</p>

    <p> </p>

    </div>

</footer>

app/views/layouts/_yeti.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Patart</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <li><%= link_to "Home", root_path, class: 'navbar-brand' %></li>
        <li><%= link_to "Contact Us", pages_contact_path, class: 'navbar-brand' %></li>
        <li><%= link_to "About Us", pages_about_path, class: 'navbar-brand' %></li>
        <li><%= link_to "create article", new_article_path, class: 'navbar-brand' %></li>
      </li>
      <% if !current_user %>
      <li class="nav-item">
        
        <li><%= link_to "Sign Up", new_user_registration_path, class: 'navbar-brand' %></li>
   	<li><%= link_to "Sign in", new_user_session_path, class: 'navbar-brand'%></li>
      </li>
      <% end %>
    </ul>
  </div>
  <% if current_user %>
  <div class="btn-group">
  <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      
       <%= current_user.username %>
      
  </button>
     <div class="dropdown-menu dropdown-menu-right">
       <button class="dropdown-item" type="button">Action</button>
       <button class="dropdown-item" type="button">Another action</button>
       <div class= 'container'>
       <li><%= link_to "Edit My Profile",edit_user_registration_path %></li>
       <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
       </div>
     </div>
  </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Patart</title>
  </head>
  <body>
    <%= render 'layouts/yeti' %>
    <%= bootstrap_flash %> 

    <div class= 'container'>
      <%= yield %>
    </div>

     <%= render 'layouts/foot' %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/_mailer.html.erb
<div class="row">
 <div class="col-md-20 col-md-offset-20">
  <div class="well">
   <%= simple_form_for @contact do |f| %>
   <%= f.input :name %>
   <%= f.input :email %>
   <%= f.input :message %>
   <%= f.submit "Get in touch!", class: "btn btn-info" %>
   <% end %>
  </div>
 </div>
</div>

app/views/pages/_test.html.erb
<!--Section: Contact v.2-->
<section class="mb-4">

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
        a matter of hours to help you.</p>

    <div class="row">

        <!--Grid column-->
        <div class="col-md-9 mb-md-0 mb-5">
            <form id="contact-form" name="contact-form" action="mail.php" method="POST">

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="name" name="name" class="form-control">
                            <label for="name" class="">Your name</label>
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="email" name="email" class="form-control">
                            <label for="email" class="">Your email</label>
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            <input type="text" id="subject" name="subject" class="form-control">
                            <label for="subject" class="">Subject</label>
                        </div>
                    </div>
                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                            <label for="message">Your message</label>
                        </div>

                    </div>
                </div>
                <!--Grid row-->

            </form>

            <div class="text-center text-md-left">
                <a class="btn btn-primary" onclick="document.getElementById('contact-form').submit();">Send</a>
            </div>
            <div class="status"></div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-3 text-center">
            <ul class="list-unstyled mb-0">
                <li><i class="fas fa-map-marker-alt fa-2x"></i>
                    <p>San Francisco, CA 94126, USA</p>
                </li>

                <li><i class="fas fa-phone mt-4 fa-2x"></i>
                    <p>+ 01 234 567 89</p>
                </li>

                <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                    <p>contact@mdbootstrap.com</p>
                </li>
            </ul>
        </div>
        <!--Grid column-->

    </div>

</section>
<!--Section: Contact v.2-->

app/views/pages/about.html.erb
<div class="row">
  <div class="col-lg-12 text-center">
     <h1>About Us</h1>
     <p class="lead">Test Text</p>
     <ul class="list-unstyled">
        <li>List Item</li>
        <li>List Item 2</li>
     </ul>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="row">
  <div class="col-lg-12 text-center">
     <h1>Contact</h1>
     <p class="lead">Test Text</p>
     <ul class="list-unstyled">
        <li>List Item</li>
        <li>List Item 2</li>
     </ul>
     <%= render 'pages/mailer' %> 
  </div>
  
</div>

app/views/pages/index.html.erb
  <!--Index Page-->
     <div class="row">

   <!-- Blog Post Content Column -->
   <div class="col-lg-8">

     <!-- Blog Post -->

     <!-- Title -->
     <h1>Blog Post Title</h1>

     <!-- Author -->
     <p class="lead">
      by <a href="#">Start Bootstrap</a>
     </p>

     <hr>

     <!-- Date/Time -->
     <p><span class="glyphicon glyphicon-time"></span> Posted on August 24, 2013 at 9:00 PM</p>

     <hr>

     <!-- Preview Image -->
     <img class="img-responsive" src="http://placehold.it/700x300" alt="">

     <hr>

     <!-- Post Content -->
     <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero,
obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi
eos magni recusandae laborum minus inventore?</p>
     <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum
quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat.
Temporibus, voluptatibus.</p>
     <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto
blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat
perspiciatis. Enim, iure!</p>
     <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas
placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem
obcaecati?</p>
     <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo,
aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam
recusandae? Qui, necessitatibus, est!</p>

     <hr>

     <!-- Blog Comments -->

     <!-- Comments Form -->
     <div class="well">
       <h4>Leave a Comment:</h4>
       <form role="form">
         <div class="form-group">
           <textarea class="form-control" rows="3"></textarea>
         </div>
         <button type="submit" class="btn btn-primary">Submit</button>
       </form>
     </div>

     <hr>

     <!-- Posted Comments -->

     <!-- Comment -->
     <div class="media">
       <a class="pull-left" href="#">
         <img class="media-object" src="http://placehold.it/64x64" alt="">
       </a>
       <div class="media-body">
         <h4 class="media-heading">Start Bootstrap
           <small>August 25, 2014 at 9:30 PM</small>
         </h4>
         Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
        </div>
      </div>

      <!-- Comment -->
      <div class="media">
        <a class="pull-left" href="#">
          <img class="media-object" src="http://placehold.it/64x64" alt="">
        </a>
        <div class="media-body">
          <h4 class="media-heading">Start Bootstrap
            <small>August 25, 2014 at 9:30 PM</small>
          </h4>
          Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          <!-- Nested Comment -->
          <div class="media">
            <a class="pull-left" href="#">
              <img class="media-object" src="http://placehold.it/64x64" alt="">
            </a>
            <div class="media-body">
              <h4 class="media-heading">Nested Start Bootstrap
                <small>August 25, 2014 at 9:30 PM</small>
              </h4>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
          </div>
          <!-- End Nested Comment -->
        </div>
      </div>

    </div>

    <!-- Blog Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Blog Search Well -->
      <div class="well">
        <h4>Blog Search</h4>
        <div class="input-group">
          <input type="text" class="form-control">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">
              <span class="glyphicon glyphicon-search"></span>
            </button>
          </span>
        </div>
        <!-- /.input-group -->
      </div>

      <!-- Blog Categories Well -->
      <div class="card my-4">
        <h4>Blog Categories</h4>
        <div class="row">
          <div class="col-lg-6">
            <ul class="list-unstyled">
 	     <li><a href="#">Category Name</a>
	     </li>
	     <li><a href="#">Category Name</a>
	     </li>
	     <li><a href="#">Category Name</a>
	     </li>
	     <li><a href="#">Category Name</a>
	     </li>
	    </ul>
	  </div>
          <div class="col-lg-6">
            <ul class="list-unstyled">
	      <li><a href="#">Category Name</a>
	      </li>
	      <li><a href="#">Category Name</a>
	      </li>
	      <li><a href="#">Category Name</a>
	      </li>
	      <li><a href="#">Category Name</a>
	      </li>
	    </ul>
	  </div>
        </div>
        <!-- /.row -->
      </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Articles</h5>
          <div class="card-body">
            <h4>Recent Posts</h4>
            <% @article.each do |a| %>
            Created by: <%= a.user.username %><br />
            <strong><%= link_to a.title, a %></strong>
   	    <p><%= truncate (a.body) %></p>
   	    <% end %>
          </div>
        </div>



    </div>

  </div>
  <!-- /.row -->
  
  <hr>